### ISSUE TITLE
Testing team

### ISSUE THREAD

**Issue by seagreen** [alexwl/haskell-code-explorer#28]
Would it be a good idea to assemble a team of testers for various platforms?

I'd be happy to be the Ubuntu tester.

**Comment by alexwl** [comment]
It is definitely a good idea.
It would also be nice to have a CircleCI build enabled for this project (I plan to work on it).

> I'd be happy to be the Ubuntu tester.

Thank you, that would be helpful.

**Comment by seagreen** [comment]
I won't have time to do regular testing, so I'm going to close this. Feel free to re-open it if you decide to build up a test team.
