### ISSUE TITLE
submodule

### ISSUE THREAD

**Issue by limengyu1990** [alexwl/haskell-code-explorer#38]
The stack project contains multiple submodules, each with its own `.stack-work/dist` directory. The `dist` directory in the root directory of the project does not have a `.stack-work` directory.
How do you index the package? Can I automatically index all submodule packages? For example: the `libs` directory and the `services` directory of the `wire` project, all submodules in these two directories have their own .stack-work directory.

https://github.com/wireapp/wire-server

**Comment by alexwl** [comment]
Currently, the indexer can only index one Cabal package at a time.

https://github.com/wireapp/wire-server repository contains many Cabal packages (all packages are listed in `wire-server/stack.yaml`).

Each Cabal package from the repository can be indexed independently. For example:

```bash
haskell-code-indexer --package ~/wire-server/services/galley
haskell-code-indexer --package ~/wire-server/services/cannon
haskell-code-indexer --package ~/wire-server/services/restund
haskell-code-indexer --package ~/wire-server/libs/api-bot
```

To start the server:

```bash
haskell-code-server -p ~/wire-server/services/galley -p ~/wire-server/services/cannon -p ~/wire-server/services/restund -p ~/wire-server/libs/api-bot --port 8080
```

**Comment by limengyu1990** [comment]
ok, I will try it, thank you.
