### ISSUE TITLE
Immediately fail on GHC mismatch

### ISSUE THREAD

**Issue by seagreen** [alexwl/haskell-code-explorer#40]
I ran `haskell-code-explorer` on a medium size project and got huge wall of error output. When I started up `haskell-code-server` only a few modules had been indexed.

It turns out the culprit was a GHC version mismatch, but I hadn't noticed the problem because the notification about it was scrolled of the screen.

Might a better default be to fail immediately when a GHC mismatch is detected?

**Comment by alexwl** [comment]
I agree it's better to fail immediately.

An attempt to index the package when versions of GHC don't match is a mistake.
