### ISSUE TITLE
Add support for Cabal-2.2.x

### ISSUE THREAD

**Issue by alexwl** [alexwl/haskell-code-explorer#5]
`cabal-helper-0.8.0.2` that is used by `haskell-code-indexer` supports only Cabal >=1.14 && <1.26 || ==2.0.*

Attempt to index a package that was built using Cabal 2.2.0.0 results in an error : `Could not find module ‘Distribution.PackageDescription.Parse’`  ([https://github.com/alexwl/haskell-code-explorer/issues/4](https://github.com/alexwl/haskell-code-explorer/issues/4))

**Comment by qrilka** [comment]
Maybe I'm missing something but didn't it work for Caba-2.2 in #3 ?

**Comment by alexwl** [comment]
I guess, the version of Cabal library is 2.0.1.0 here:
/home/qrilka/ws/h/xeno/.stack-work/dist/x86_64-linux-tinfo6/**Cabal-2.0.1.0**/setup-config

**Comment by qrilka** [comment]
Ouch, sorry for the noise then :)

**Comment by alexwl** [comment]
[https://github.com/alexwl/haskell-code-explorer/commit/730fc6b033548b329ae70a8bfe7b08620ecf9eb8](https://github.com/alexwl/haskell-code-explorer/commit/730fc6b033548b329ae70a8bfe7b08620ecf9eb8) adds support for GHC 8.4.3 and Cabal 2.2.  GHC 8.4.3 and Cabal 2.4 might work, but I haven't tested it yet.
